### ISSUE TITLE
Removing vertices from graph

### ISSUE THREAD

**Issue by arturom** [optiver/ruruki#69] opened 2017-05-17 21:23 UTC
I may be missing something in the documentation, but I cannot seem to be able to remove a vertex from a graph.

Below a simple example where I add two vertices to a graph, then I remove one vertex, then I display the contents of the graph and I still see the vertex I just removed.

```python
from ruruki.graphs import Graph


# Initialize graph
g = Graph()
g.add_vertex_constraint('facility', 'uid')

# Add two 'facility' vertices
f1 = g.add_vertex('facility', uid='FAC_01', name='Facility 01')
f2 = g.add_vertex('facility', uid='FAC_02', name='Facility 02')

# Display all 'facilty' vertices
print(f1.is_bound())
for f in g.get_vertices('facility').all():
    print(f, f.properties)

# Remove vertex 'f1'
g.remove_vertex(f1)

# Display all 'facility' vertices again
print(f1.is_bound())
for f in g.get_vertices('facility').all():
    print(f, f.properties)
```

And the script output:
```
True
<Vertex> 1 {'uid': 'FAC_02', 'code': 'FAC_02', 'name': 'Facility 02'}
<Vertex> 0 {'uid': 'FAC_01', 'code': 'FAC_01', 'name': 'Facility 01'}
True
<Vertex> 1 {'uid': 'FAC_02', 'code': 'FAC_02', 'name': 'Facility 02'}
<Vertex> 0 {'uid': 'FAC_01', 'code': 'FAC_01', 'name': 'Facility 01'}
```

I was expecting `FAC_01` to disappear from the second set of outputs. Any suggestions?

**Comment by jenmud** [comment] 2017-05-17 21:56
Thanks for raising this issue Arturo, I will investigate and get back to you hopefully by the end of today.

Sorry for the inconvenience.

Jenda

**Comment by arturom** [comment] 2017-05-18 01:36
Thanks for sharing ruruki and investigating the issue.
Ruruki seems like the in-memory graph in Python I was searching for!

**Comment by jenmud** [comment] 2017-05-18 02:07
No worries only a pleasure. I am super pleased you find it useful.

**Comment by jenmud** [comment] 2017-05-18 10:21
@arturom thanks for raising this issue again. I have added in a bug fix for this issue and created a pull request for Optiver to merge it.

In the meantime, I will upload the new version to pypi, alternatively please [clone my fork of ruruki](https://github.com/jenmud/ruruki) for immediate response because the new maintainers at Optiver will most likely not be actively looking at this repository.

```bash
  @load
  Scenario: Removing a vertex from the graph                                       # test_behave/graph.feature:56
    Given we have a empty graph object                                             # test_behave/steps/graphs.py:11 0.000s
    Given we have a file object with the following dump content                    # test_behave/steps/graphs.py:22 0.000s
      """
          {
              "constraints": [
                  {
                      "key": "uid",
                      "label": "facility"
                  }
              ],
              "edges": [],
              "vertices": [
                  {
                      "id": 0,
                      "label": "facility",
                      "metadata": {
                          "in_edge_count": 0,
                          "out_edge_count": 0
                      },
                      "properties": {
                          "name": "Facility 01",
                          "uid": "FAC_01"
                      }
                  },
                  {
                      "id": 1,
                      "label": "facility",
                      "metadata": {
                          "in_edge_count": 0,
                          "out_edge_count": 0
                      },
                      "properties": {
                          "name": "Facility 02",
                          "uid": "FAC_02"
                      }
                  }
              ]
          }
      """
    When we load the dump into the database                                        # test_behave/steps/graphs.py:34 0.000s
    And we remove vertex "0"                                                       # test_behave/steps/graphs.py:45 0.000s
    Then we expect the vertex "0" to be removed from the graph vertices entity set # test_behave/steps/graphs.py:52 0.000s
    And we expect vertex "0" to be unbound                                         # test_behave/steps/graphs.py:63 0.000s
```

**Closed by jenmud** 2017-05-18 10:21 UTC
Labels: bug

**Comment by jenmud** [comment] 2017-05-18 10:35
@arturom ruruki v1.4.1 is available [pypi](https://pypi.python.org/pypi/ruruki/1.4.1)

**Comment by arturom** [comment] 2017-05-19 16:30
Thanks! It works like a charm.
I noticed that trying to add a new vertex using the same constraint of a deleted vertex results in an error. Is this by design?

Using `graph.get_or_create_vertex()` using the same constraint of a deleted verted does not result in an error, but it doesn't add the vertex back to the graph either.

**Comment by jenmud** [comment] 2017-05-20 01:33
This is not by design, and yet another good catch @arturom. I will test it and see if I can reproduce it, and add in a fix.

Thanks for raising these issues. They are use cases that I have not needed to do.

I will create another ticket for this problem. But instead I will create it on my fork.

**Comment by jenmud** [comment] 2017-05-20 01:46
See bug ticket: https://github.com/jenmud/ruruki/issues/2

**Comment by jenmud** [comment] 2017-05-20 04:44
@arturom I have added in a bug fix as per ticket https://github.com/jenmud/ruruki/issues/2 and uploaded a new version v1.4.2 to pypi.

Please let me know if you have any other issues. If you do, please create a ticket on my repo.
